Updated docstrings for multiples modules.
kbandla/dpkt pull request #623
Opened 2022-02-06 02:08 UTC by reaal-dev

Update docstring that had a TODO for multiple modules in a major part in the description of classes and headers attributes

2022-02-08 09:24 UTC, obormot requested changes
Minor fixes requested here and there, great job overall!

2022-02-08 09:24 UTC, obormot commented on dpkt/icmp.py
> +    is indicated when a requested service is not available or that a host or router could not be reached.
"when an error?" looks like a typo/extra word

2022-02-08 09:24 UTC, obormot commented on dpkt/netflow.py
> +    of congestion. A typical flow monitoring setup (using NetFlow) consists of three main components.
> A typical flow monitoring setup (using NetFlow) consists of three main components.

irrelevant here, IMO

2022-02-08 09:24 UTC, obormot commented on dpkt/radiotap.py
> +    In this section we'll have a look how the IEEE 802.11 protocol is implemented in libtins. libtins has great support
looks like a copy-pasta..   please rework this description

2022-02-08 09:24 UTC, obormot commented on dpkt/pppoe.py
> +    A 2005 networking book noted that "Most DSL providers use PPPoE, which provides authentication, encryption, and
> A 2005 networking book noted that "Most DSL providers use PPPoE, which provides authentication, encryption, and compression." 

Irrelevant here, IMO

2022-02-08 09:24 UTC, obormot commented on dpkt/udp.py
> +            sport: (int): (2 bytes)
Missing field descriptions here

2022-02-08 09:24 UTC, obormot commented on dpkt/ip6.py
> +            _v_fc_flow: (int): Version (4 bits), Traffic Class (6+2 bits) and Flow Label (20 bits).
`_v_fc_flow` is an internal ("private") name for the attribute. 
The fields should be documented separately, e.g.
```
v (int): Version (4 bits)
fc (int): Traffic Class (6+2 bits)
flow (int): Flow Label (20 bits)
```

2022-02-08 09:24 UTC, obormot commented on dpkt/ip.py
> +        _v_hl: (int): Version (4 bit) For IPv4, this is always equal to 4 and Internet Header Length (IHL) (4 bit)
`_v_hl` is an internal ("private") name for the attribute. 
The fields should be documented separately, e.g.
```
v (int): Version (4 bits)
hl (int): Internet Header Length (IHL) (4 bits)
```

2022-02-08 09:24 UTC, obormot commented on dpkt/ip.py
> +        _flags_offset: (int): Flags (3 bit) and Fragment offset (13 bit)
see comment for `_v_hl`, same applies.  also 3 bit -> 3 bits.   13 bit -> 13 bits

2022-04-08 07:14 UTC, obormot commented
@reaal-dev Just checking in. Are you planning to address the review comments? We won't be able to merge before that.  Thanks!

2022-04-08 12:26 UTC, reaal-dev commented on dpkt/ah.py
> +    However, AH does not provide data confidentiality, which means that all of your data is sent in the clear.
Removed 2nd sentence

2022-04-08 12:27 UTC, reaal-dev commented on dpkt/dpkt.py
> +    class Foo(Packet):
Removed changes.

2022-04-08 12:27 UTC, reaal-dev commented on dpkt/cdp.py
> +            ttl: (int): TIme to live. The amount of time in seconds that a receiver should retain the information
Fixed

2022-04-08 12:27 UTC, reaal-dev commented on dpkt/dhcp.py
> +            secs: (int): Seconds. This is second elapsed since client started the address acquisition or
Corrected

2022-04-08 12:28 UTC, reaal-dev commented on dpkt/dns.py
> +        """int: Authoritative Answer. 1 bit.
Removed "int:"

2022-04-08 12:28 UTC, reaal-dev commented on dpkt/dns.py
> +        """int: Truncated. 1 bit. Indicates that only the first 512 bytes of the reply was returned."""
Removed "int:"

2022-04-08 12:28 UTC, reaal-dev commented on dpkt/http.py
> +     of the protocol, these messages were openly sent across the connection. In HTTP/2, the once human-readable message
Removed lines

2022-04-08 12:28 UTC, reaal-dev commented on dpkt/icmp.py
> +    is indicated when a requested service is not available or that a host or router could not be reached.
Removed example

2022-04-08 12:35 UTC, reaal-dev commented on dpkt/netflow.py
> +    of congestion. A typical flow monitoring setup (using NetFlow) consists of three main components.
Removed "A typical..."

2022-04-08 12:35 UTC, reaal-dev commented on dpkt/radiotap.py
> +    In this section we'll have a look how the IEEE 802.11 protocol is implemented in libtins. libtins has great support
Removed description for now

2022-04-08 12:35 UTC, reaal-dev commented on dpkt/pppoe.py
> +    A 2005 networking book noted that "Most DSL providers use PPPoE, which provides authentication, encryption, and
Removed

2022-04-08 12:35 UTC, reaal-dev commented on dpkt/udp.py
> +            sport: (int): (2 bytes)
Added descriptions

2022-04-08 12:37 UTC, reaal-dev commented on dpkt/dhcp.py
> +            op: (int): Operation. This is called operation field and it identify the message type
Replaced by RFC 2131 definition

2022-04-08 12:39 UTC, reaal-dev commented on dpkt/ip6.py
> +            _v_fc_flow: (int): Version (4 bits), Traffic Class (6+2 bits) and Flow Label (20 bits).
Added as follows. Please advise.

_v_fc_flow:
     v (int): Version (4 bits)
     fc (int): Traffic Class (6+2 bits)
     flow (int): Flow Label (20 bits)

2022-04-08 12:40 UTC, reaal-dev commented on dpkt/ip.py
> +        _v_hl: (int): Version (4 bit) For IPv4, this is always equal to 4 and Internet Header Length (IHL) (4 bit)
Added in format described for _v_fc_flow in ip6

2022-04-08 12:40 UTC, reaal-dev commented on dpkt/ip.py
> +        _flags_offset: (int): Flags (3 bit) and Fragment offset (13 bit)
Added in format described for _v_fc_flow in ip6

2022-04-08 12:41 UTC, reaal-dev commented
Thanks for the reminder

2022-04-08 17:49 UTC, obormot commented on dpkt/ip6.py
> +            _v_fc_flow: (int): Version (4 bits), Traffic Class (6+2 bits) and Flow Label (20 bits).
Looks good, except for the order. _v_fc_flow fields should appear before plen, not at the end. Same for the ip header

2022-04-08 19:49 UTC, obormot commented
Most everything looks good now. Please address the order of fields in ip and ip6 and we're good to merge.

2022-04-09 17:38 UTC, obormot approved these changes

2022-04-09 17:44 UTC, merged