modpcap reader support
kbandla/dpkt pull request #633
Opened 2022-06-17 17:56 UTC by oosthoek

support for modified pcaps
https://wiki.wireshark.org/Development/LibpcapFileFormat#modified-pcap

2022-06-18 21:46 UTC, obormot requested changes

2022-06-18 21:46 UTC, obormot commented on dpkt/pcap.py
> +        return PktHdr(self.pkt_hdr_buf)
why wouldn't this return the full mod header?

2022-06-18 21:46 UTC, obormot commented on dpkt/pcap.py
> +        self._divisor = 1E6 if magic in (TCPDUMP_MAGIC, PMUDPCT_MAGIC) else Decimal('1E9')
the new magic should be added here I think, or better reverse the logic:
```
self._divisor = Decimal('1E9') if magic in (TCPDUMP_MAGIC_NANO, PMUDPCT_MAGIC_NANO) else 1E6
```

2022-06-18 21:46 UTC, obormot commented on dpkt/pcap.py
> +
extra whitespace

2022-06-18 21:46 UTC, obormot commented on dpkt/pcap.py
> +
extra whitespace

2022-06-18 21:46 UTC, obormot commented on dpkt/pcap.py
> +
extra whitespace

2022-06-18 21:48 UTC, obormot commented on dpkt/pcap.py
> +def test_reader_modified_pcap_type():
needs 1 extra whitespace before function def

2022-06-18 21:55 UTC, obormot commented on dpkt/pcap.py
> +        ('pkt_hdr_buf', f"{PktHdr.__hdr_len__}s", PktHdr.__hdr_len__ * b'\x00'),
f-strings aren't supported by all versions of python in dpkt's build pipeline I think

2022-06-22 21:37 UTC, obormot requested changes

2022-06-22 21:37 UTC, obormot commented on dpkt/pcap.py
> +        return PktHdr(self.pkt_hdr_buf)
yeah I'd rather not add the `get_hdr()` method to the existing `PktHdr` class for this reason alone, I don't think this is justified.  I'd just duplicate the orig fields in the new header
```
class PktModHdr(dpkt.Packet):
    ...
    __hdr__ = (
        ('tv_sec', 'I', 0),
        ('tv_usec', 'I', 0),
        ('caplen', 'I', 0),
        ('len', 'I', 0),
        ('ifindex', 'I', 0),
        ('protocol', 'H', 0),
        ('pkt_type', 'B', 0),
        ('pad', 'B', 0),
    )
```
this reads cleaner and doesn't change the existing code.

2022-06-23 17:47 UTC, obormot approved these changes

2022-06-23 17:49 UTC, obormot commented
Thanks for your contribution @oosthoek !

2022-06-23 17:55 UTC, merged

2022-06-23 18:05 UTC, oosthoek commented
@obormot thanks!  is there a pypi release planned anytime soon?

2022-06-23 20:37 UTC, obormot commented
Don't have it planned, but I've just created https://github.com/kbandla/dpkt/issues/634 to get it started when @brifordwylie or I get time to dedicate. Hopefully soon!